apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-multiservice-environments
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/automationiberia/umbrella-demo.git
      revision: HEAD
      directories:
      - path: environments
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/automationiberia/umbrella-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
